name = "BatchPDLP"
uuid = "529b9e8a-d2db-4a93-8026-567587707ce3"
authors = ["Robert X. Gottlieb <robert.x.gottlieb@uconn.edu>", "Dimitri Alston <dimitri.alston@uconn.edu>", "Matthew D. Stuber <matthew.stuber@uconn.edu>"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[compat]
CUDA = "5"
julia = "1.10"